language: node_js
arch:
  - amd64
  - arm64  # please note arm64-graviton2 requires explicit virt: [lxd|vm] tag so it's recommended for jobs.include, see below
  - ppc64le
  - s390x
node_js:
  - 12
script: npm run test:coverage
after_success: npm run coveralls
